In [1]:
!python -m pip install --user --upgrade git+https://github.com/scikit-hep/boost-histogram.git@develop

  Cloning https://github.com/scikit-hep/boost-histogram.git (to develop) to /tmp/pip-9rzao8fu-build
done
You are using pip version 10.0.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [1]:
import boost.histogram as bh
import numpy as np

In [2]:
vals = np.random.normal(size=(2,1000000))

In [3]:
hist = bh.histogram(bh.axis.regular_sqrt(10,0,10, label='x'),
                    bh.axis.circular(10,0,1, label='y'))
hist

histogram(
  regular_sqrt(10, 0, 10, metadata="x", options=underflow | overflow),
  regular(10, 0, 1, metadata="y", options=overflow | circular)
)

This fills the histogram

In [4]:
hist(*vals)

Let's just take a quick look at the bin contents:

In [5]:
print(np.asarray(hist))

[[    0     0     0     0     0     0     0     0     0     0     0]
 [ 4014  3980  3931  3914  4028  3972  4025  3954  4068  3951     0]
 [11714 11389 11495 11651 11719 11520 11664 11486 11620 11633     0]
 [15926 16014 15930 15878 15989 16014 16127 16076 15926 16047     0]
 [12934 12753 12829 13103 12898 13067 12964 12852 12953 12673     0]
 [ 4909  4775  4915  4960  4905  4960  4869  4848  4867  4846     0]
 [  600   640   582   611   606   584   649   613   596   586     0]
 [   14    11    16    17    16    16     6    17    17    15     0]
 [    0     0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0     0]
 [49960 50023 49971 49852 50216 49907 49959 50017 50192 50156     0]]
